services:
  storage:
    image: redis
    volumes:
      - ./src/data:/data
  counter:
    image: zicio/bookscounter
    environment:
      - PORT=3100
      - REDIS_URL=redis://storage
    ports:
      - 3100:3100
  app:
    build: ./
    environment:
      - PORT=4200
      - COUNTER_URL=http://counter:3100/counter
    ports:
      - 4200:4200
    depends_on:
      - storage
      - counter
